dist: trusty
sudo: required
services:
   - docker

env:
  global:
    - ROOTDIR="$TRAVIS_BUILD_DIR"

before_install:
  - docker build -t crawl2_ci_image .
  - docker run -dit -v $TRAVIS_BUILD_DIR:/tmp/crawl2_ci --name crawl2_ci_container crawl2_ci_image /bin/bash

cache:
  directories:
    - work

script:
  - docker exec crawl2_ci_container /bin/bash -c 'cd /tmp/crawl2_ci; ./gradlew assemble --info'
